shallow_clone: false
skip_branch_with_pr: true
clone_depth: 1

environment:
  global:

  matrix:
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python34-x64"
    - python: "C:/Python34"
    - python: "C:/Python35-x64"
    - python: "C:/Python35"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  - ps: pip install --upgrade pip wheel
  - ps: pip --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - ps: pip install coverage haas cython
  - ps: pip install -r test-requirements
  - ps: pip freeze

build_script:
  - ps: python setup.py build_ext --inplace --zmq=$ZMQ
  - ps: pip install -e .

test_script:
  - ps: md temp
  - ps: cd temp
  - cmd: python -c "import zmq; print(zmq.zmq_version())"'
  - cmd: python -um haas pyzmq
